# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'stargazer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for stargazer
  pod 'Alamofire', '~> 5.2'

  target 'stargazerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'stargazerUITests' do
    # Pods for testing
  end

end
